services:
  - type: web
    name: flashpeg-arbitrage
    runtime: python
    buildCommand: pip install -r requirements-flask.txt
    startCommand: gunicorn wsgi:app
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"